### ISSUE TITLE
Public docs - Planning

### ISSUE THREAD

**Issue by widal001** [cofundable/cofundable#26]
### Summary

Record the answers to a series of architectural and design questions about how we approach managing Cofundable's public docs.

### User stories

- As a project maintainer, I want...
  - to be able to edit the docs with a "what you see is what you get" (WYSIWYG) interface, so that I can know what the output will look like as I'm drafting the content.
  - the content of the docs to be stored in a public repository, so that users and open source contributors can suggest changes or additions.
  - the docs to have a similar branding and color scheme to our website and frontend application, so that all of our platforms have a unified identity and provide users with a cohesive experience.
- As an open source contributor, I want...
  - to be able to recommend changes to the docs, so that I can fix information that it's incorrect or help fill in holes in the documentation.
- As a user, I want...
  - to be able to search for information across all of the pages in the docs, so that I don't have to manually search through each page to find what I'm looking for.
  - the docs to be aesthetically pleasing and user friendly, so that I can focus on finding what I need instead of figuring out how to navigate the site.

### Open questions

- Which tool or platform should we to create and manage the public docs?
- Should we create a separate repository for public docs or combine them with another repository?

### Sub-tasks

- [ ] [ADR] Documentation platform
- [ ] [ADR] Documentation repo

### Acceptance criteria

- [ ] Answers to the questions listed above have been documented publicly in one or more ADRs
- [ ] Follow-up tickets have been created to implement these decisions (as needed)
