### ISSUE TITLE
Milestone: Static Site

### ISSUE THREAD

**Issue by widal001** [cofundable/cofundable#5]
### Definition of Done

- [ ] The source code for a static website is hosted at `cofundable/cofundable-website`
- [ ] The site has been published using Netlify and is accessible at www.cofundable.org
- [ ] The website has the following pages
  - [ ] Home page
  - [ ] Help & Docs
- [ ] The website also allows people to sign up for updates

### Not in Scope

- The first iteration of the website does not include a blog or any other features
- The first iteration of the website won't have integration or unit testing

### Assumptions, Constraints, and Risks

- The code for the static site may eventually be moved to or combined with another repo (e.g. blog, frontend, etc.)
- The framework chosen for this iteration of the static site (eleventy) may need to be substituted for a different framework (nuxt.js or next.js) in a future iteration
- Adopting a less common framework may make it difficult to migrate in the future
- The first iteration needs to be hosted for free

## Sub-tasks

- [ ] Create repo for static site: `cofundable/cofundable-website`
- [ ] Build the homepage
- [ ] Build the help & docs page
- [ ] Add branding graphics and styling
